namespace fyd.backend.Dominio.General.Valores
{
    public record InfoAgenda(
        int? EmpresaId,
        string Nombre,
        string Nombre2,
        string Titulo,
        string Calle,
        int? Altura,
        string PisoDpto,
        string Barrio,
        int LocalidadId,
        string Cp,
        int TipoDocId,
        string NumeroDoc,
        string Ib,
        string Email1,
        string Email2,
        string Email3,
        string Email4,
        string Web,
        string TipoTelefono1,
        string Telefono1,
        string TipoTelefono2,
        string Telefono2,
        string TipoTelefono3,
        string Telefono3,
        string TipoTelefono4,
        string Telefono4,
        string TipoTelefono5,
        string Telefono5,
        string Variable1,
        string Variable2,
        string Variable3,
        string Variable4,
        bool CorrespondenciaOk,
        int CorrespondenciaId,
        string Atencion,
        bool CliDomEntregaOk,
        string Memo
    );
}
